### ISSUE TITLE
gerrit push errors

### ISSUE THREAD

**Issue by nicknitewolf** [LineageOS/temp_infra_tracker#7]
git push --no-thin needs to be added if not cannot push.

**Comment by nicknitewolf** [comment]
error: unpack failed: error Missing tree e9e9074e130ac89f0d9fd501b850cfafe0efec16
fatal: Unpack error, check server log
To ssh://nicknitewolf@review.lineageos.org:29418/LineageOS/android_device_wingtech_wt88047
 ! [remote rejected] HEAD -> refs/for/cm-14.1 (n/a (unpacker error))
error: failed to push some refs to 'ssh://nicknitewolf@review.lineageos.org:29418/LineageOS/android_device_wingtech_wt88047'

**Comment by zifnab06** [comment]
Not an issue on our end, I've successfully cloned that repo and pushed a patchset.
